#!/usr/bin/env Rscript
# Regenerate _variables.yml from the plant pin in renv.lock, so theory pages
# can stamp which plant build they describe via `{{< var plant.version >}}`
# etc. — an R-free mechanism that renders even on non-executing (eval:false)
# pages, and stays in sync with the machine pin instead of being hand-typed.
#
# Run whenever renv.lock's plant entry changes (e.g. after refresh.yml bumps
# plant), then commit _variables.yml. Prints the values written.
#   Usage: Rscript R/sync_plant_vars.R [renv.lock]

`%||%` <- function(a, b) if (is.null(a)) b else a

args      <- commandArgs(trailingOnly = TRUE)
lock_path <- if (length(args)) args[[1]] else "renv.lock"
out_path  <- "_variables.yml"

lock <- jsonlite::fromJSON(lock_path, simplifyVector = FALSE)
p <- lock$Packages$plant
if (is.null(p)) stop("No 'plant' entry in ", lock_path, call. = FALSE)

version  <- p$Version %||% "unknown"
sha_full <- p$RemoteSha %||% p$RemoteRef %||% ""
sha      <- if (nzchar(sha_full)) substr(sha_full, 1, 7) else "unpinned"
user     <- p$RemoteUsername %||% "traitecoevo"
repo     <- p$RemoteRepo %||% "plant"
commit_url <- if (nzchar(sha_full)) {
  sprintf("https://github.com/%s/%s/commit/%s", user, repo, sha_full)
} else {
  sprintf("https://github.com/%s/%s", user, repo)
}
# The .9xxx fourth component is R's dev-version convention (a build off an
# unreleased branch), as opposed to a tagged release like 2.1.0.
build <- if (grepl("\\.9[0-9]{3}$", version)) "development build" else "release"

lines <- c(
  "# Generated by R/sync_plant_vars.R from renv.lock — do not edit by hand.",
  "# The plant build the site renders against; stamped onto theory pages via",
  "# `{{< var plant.version >}}`. Regenerate when renv.lock's plant pin changes.",
  "plant:",
  sprintf('  version: "%s"', version),
  sprintf('  sha: "%s"', sha),
  sprintf('  sha_full: "%s"', sha_full),
  sprintf('  commit_url: "%s"', commit_url),
  sprintf('  build: "%s"', build)
)
writeLines(lines, out_path)
cat("Wrote", out_path, "\n")
cat(paste(lines[-(1:3)], collapse = "\n"), "\n")
